  
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in paralle
jobs:
    build:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Compile LateX
        uses: vinay0410/tectonic-action@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tex_path: 'report/main.tex'
          push: 'yes'
      - name: Compile LateX
        uses: vinay0410/tectonic-action@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tex_path: 'presentation/main.tex'
          push: 'yes'